export function Footer() {
    return (
        <footer>
            <nav><ul>
                <li>
                    <a>
                        Teste
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a>
                        Teste
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a>
                        Teste
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a>
                        Teste
                    </a>
                </li>
            </ul></nav>
        </footer>
    )
}